### ISSUE TITLE
[Feature]: Enable for GitHub Enterprise

### ISSUE THREAD

**Issue by actuarysailor** [andrewthetechie/gha-repo-manager#16]
**Is your feature request related to a problem? Please describe.**
It currently connects to GitHub even if running from another GitHub site like GitHub Enterprise.

**Describe the solution you'd like**
Ability to connect to other GitHub Websites - as seen [here](https://pygithub.readthedocs.io/en/latest/introduction.html)

**Describe alternatives you've considered**
It's either update your repo, or build my own from scratch.

**Additional context**
![image](https://github.com/andrewthetechie/gha-repo-manager/assets/24359398/08630891-3990-47d4-8c40-6d33dcdf8870)

**Comment by andrewthetechie** [comment]
I'll take a look at adding this feature today.

**Comment by andrewthetechie** [comment]
@actuarysailor I've released v1.6.0 with support for Github Enterprise. It adds a new input variable, `github_server_url `, you can set to declare your API URL explicitly. If `github_server_url` is left at its default, the action will try to discover the API URL using `GITHUB_SERVER_URL` from the environment.

Can you try it with your Github Enterprise environment and let me know if it works for your use case?

**Comment by actuarysailor** [comment]
@andrewthetechie  - seems to be mostly working.

I get this error when I try to do anything with status check requirements or requiring the branch be up to date for branch policies:
![image](https://github.com/andrewthetechie/gha-repo-manager/assets/24359398/d65df357-30c4-47da-8460-9e2d6d738815)

Here is a sample of the settings.yaml where I had simplified it as much as possible; expecting it to work.

![image](https://github.com/andrewthetechie/gha-repo-manager/assets/24359398/bac426d9-9a84-4d95-b6d6-f599a8f372f4)

If I remove / comment out the block completely it works.

I don't think this is an issue particular to GHE.  So I would say it is working for GHE.

**Comment by andrewthetechie** [comment]
Glad to hear it's mostly working. I'll close this issue.

If you continue to run into problems with status checks, feel free to open another issue with as much detail as possible on the error.

**Comment by actuarysailor** [comment]
> Glad to hear it's mostly working. I'll close this issue.
> 
> If you continue to run into problems with status checks, feel free to open another issue with as much detail as possible on the error.

I actually made a small pull request to address the status check issue.  Super basic code change; but you may not like the order of my ternery functions to handle nulls.  Definitely was able to run into errors when the config yaml has settings and the REST API returns null; the check has good pre-handling for the yaml config nulls but not the GitHub nulls.
