### ISSUE TITLE
Better Logging of Differences

### ISSUE THREAD

**Issue by actuarysailor** [andrewthetechie/gha-repo-manager#29]
**Is your feature request related to a problem? Please describe.**
Feature - right now the GitHub agent output just says "Differences Detected"; it would be nice if it spit out the JSON summary of differences you calculate.

**Describe the solution you'd like**
Summary of the differences in the Agent log.

**Describe alternatives you've considered**
Other repos / GitHub actions - honestly I looked, and yours is the best one out there.

**Additional context**
None - I may help code this as well.

**Comment by andrewthetechie** [comment]
Hi @actuarysailor,

The action currently has two outputs: result and diff. Diff is a JSON encoded string of the changes the action made. 

Does that fulfill your needs?

**Comment by actuarysailor** [comment]
@andrewthetechie  - Let me double check; I saw the JSON in my debugging, but it seemed like it wasn't writing to the agent output.  Maybe it's in the agent log and not the terminal?  I don't normally look at the logs unless I see big issues with the terminal kanbans.

**Comment by actuarysailor** [comment]
@andrewthetechie - yea, I don't see the JSON dumped to the log:

![image](https://github.com/andrewthetechie/gha-repo-manager/assets/24359398/1222ce62-59b4-481b-809a-0c38760f89e5)

**Comment by andrewthetechie** [comment]
Will be released in https://github.com/andrewthetechie/gha-repo-manager/pull/26
