### ISSUE TITLE
[BUG]: Repository JSON null but Config YAML not

### ISSUE THREAD

**Issue by actuarysailor** [andrewthetechie/gha-repo-manager#31]
**Describe the bug**
If the Config settings are not null, but the settings in the YAML are you get errors when it tries to reference values in the repo settings.

**To Reproduce**
1. Set all your PR Options in a repo to none - remove all status checks, overrides, etc.
2. Configure Settings.YAML to populate status checks and who can close / override pull request options etc.
3. Run the action'

**Expected behavior**
It should show them as a difference rather than throwing an error because a dictionary key is missing.

**Screenshots**
Sorry, didn't take any, but provided steps to reproduce.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version 101.0.1210.39 (Official build) (64-bit)

**Additional context**
Came across it when I was testing the PR for status checks.  That PR has this fixed.
Fixed in #28

**Comment by andrewthetechie** [comment]
Will be released in https://github.com/andrewthetechie/gha-repo-manager/pull/26
