### ISSUE TITLE
[BUG]: Populating Checks in YAML does nothing

### ISSUE THREAD

**Issue by actuarysailor** [andrewthetechie/gha-repo-manager#32]
**Describe the bug**
If you populate the list of required status checks for Pull Requests, it does nothing.

**To Reproduce**
1. Remove all status checks from repo
2. Add them back to the YAML
3. Run the action
4. See that your repo still has no required status checks

**Expected behavior**
Status checks should be added and marked as required in the branch protection policies

**Screenshots**
Gave steps above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 101.0.1210.39 (Official build) (64-bit)
 
**Additional context**
Fixed in #28

**Comment by andrewthetechie** [comment]
Will be released in https://github.com/andrewthetechie/gha-repo-manager/pull/26
