### ISSUE TITLE
[BUG]: Lists compared between config and repo flag false negatives

### ISSUE THREAD

**Issue by actuarysailor** [andrewthetechie/gha-repo-manager#33]
**Describe the bug**
When comparing the lists in JSON - e.g. users, teams, and required status checks - the action falsely flags them as differences when they are sorted in different orders.

**To Reproduce**
1. Add status checks to branch protection
2. Make sure they get added to the YAML in a different order
3. Run program check and it will say there are differences detected.

**Expected behavior**
Should be no differences.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version 101.0.1210.39 (Official build) (64-bit)

**Additional context**
Fixed in #28

**Comment by andrewthetechie** [comment]
Will be included in https://github.com/andrewthetechie/gha-repo-manager/pull/26
